repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        exclude: ^tests/|libmozdata/modules.json
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-coding==1.3.2
          - flake8-copyright==0.2.4
          - flake8-debugger==4.1.2
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: trailing-whitespace
        exclude: ^tests/uplift/|^tests/html/
      - id: check-yaml
      - id: mixed-line-ending
        exclude: ^tests/html/
      - id: name-tests-test
        args: ["--django"]
        exclude: tests/auto_mock.py
      - id: check-json
        exclude: ^tests/mocks/
      - id: requirements-txt-fixer
      - id: check-vcs-permalinks
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        exclude: libmozdata/modules.json
  - repo: https://github.com/marco-c/taskcluster_yml_validator
    rev: v0.0.10
    hooks:
      - id: taskcluster_yml
  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa
  - repo: meta
    hooks:
      - id: check-useless-excludes
default_language_version:
  python: python3
